name: Release

# on events
on:
  push:
    tags:
      - v*

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          lfs: 'true'

      - name: Pull Git LFS Files
        uses: actions/checkout@v2

      - run: git lfs pull

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        env:
          CGO_ENABLED: "0"
        with:
          platforms: 'linux/amd64, linux/arm64, darwin/amd64, windows/amd64' # linux/386, linux/arm are not supported
          package: 'cmd/livekit-cli'
          dest: 'dist'
          name: 'livekit-cli'

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        env:
          CGO_ENABLED: "0"
        with:
          platforms: 'linux/amd64, linux/arm64, darwin/amd64, windows/amd64' # linux/386, linux/arm are not supported
          package: 'cmd/livekit-load-tester'
          dest: 'dist'
          name: 'livekit-load-tester'

      - name: Release
        uses: softprops/action-gh-release@v0.1.8
        with:
          files: dist/*
